### ISSUE TITLE
Setups for jest-tobetype

### ISSUE THREAD

**Issue by eddie0329** [abritinthebay/jest-tobetype#16]
## 📌  Issue

Cannot extend in jest set up file.

## 📌 Way to do

Because extending in `setupTestFrameworkScriptFile`, which explained in README, is deprecated, i extend jest-tobetype in `setupFilesAfterEnv`. 

But still, it does using toBeType is not defined. 

Is there any solution for this?

**Comment by abritinthebay** [comment]
Fixed with your merge, will release soon.
