### ISSUE TITLE
Parameter name mismatch

### ISSUE THREAD

**Issue by maxp** [abritinthebay/jest-tobetype#8]
The `expected` parameter
https://github.com/abritinthebay/jest-tobetype/blob/master/index.js#L6
declared before as 'argiment'
https://github.com/abritinthebay/jest-tobetype/blob/master/index.js#L4

**Comment by abritinthebay** [comment]
🙀

Good catch. Wtf. Will fix this weekend.

**Comment by abritinthebay** [comment]
Fixed in v1.2.1, freshly out.
